const axios = require('axios');

function downloadMovie(movieName) {
    // return the promise generated by axios when calling `axios.get` 
    // to download information about movie name.
   return axios
    .get('http://omdbapi.com/?s=Star%20Wars')
    .then(response => response.data.search)
}

const movies = ['Star Wars', 'Lord of the Rings', 'Transformers']

// declare an array called promises
const promises = [];
// write a for loop to iterate over each string in the movies array, 
// pushing the returned promise from downloadMovie to the promises array


// for (var i = 0; i < movies.length; i++) {
//     const promises = downloadMovie(movies[1]);
//     promise.push(promise);
// }

const promises = movies.map(downloadMovie);

// after the loop, use Promise.all().then() to wait for all promises to finish.
Promise
.all(promises)
.then(data => {
    console.log(data[0]);
    console.log(data[1]);
    console.log(data[2]);
});